queue_rules:
  - name: default
    conditions: []  # no extra conditions needed to get merged

pull_request_rules:
  - name: merge using the merge queue
    conditions:
      - base=main
      - check-success=pr-merge - Pull Request
      - check-success=pr-head - Pull Request
    actions:
      queue:
        name: default
